# fly.toml app configuration file generated for pinit on 2023-07-27T12:32:40+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pinit"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  cmd = ["start_with_migrations.sh"]
  entrypoint = ["sh"]

[env]
  BASE_URL = "https://pinit.fly.dev"
  DATABASE_URL = "file:/data/sqlite.db"
  PORT = "8080"

[[mounts]]
  source = "data"
  destination = "/data"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
