name: Nodejs

on:
  push:

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "file:./test.db"
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install tools
      uses: jdx/mise-action@v2

    - name: Install node dependencies
      run: npm ci

    - name: Create test DB
      run: npm run db:migrate:test

    - name: Run unit tests
      run: npm run test:unit run

    - name: Run e2e tests
      run: npm run cypress:run

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [unit_test]
    if: github.ref == 'refs/heads/master'
    permissions:
      packages: write
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Install tools
      uses: jdx/mise-action@v2

    - name: Set up Docker Buildx for cache
      uses: docker/setup-buildx-action@v3

    - name: Expose GitHub Runtime for cache
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Set up Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:deploy

    - name: Build, push and deploy
      run: kamal deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
